gems:
  - jekyll-mentions
  - jekyll-sitemap

footer-links:
  github: nicolasbock

pages_list:
  Main: "/spamm-miniapp/"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

url: http://www.freeon.org/spamm-miniapp
baseurl: "/spamm-miniapp"
